// Supabase Edge Function: kyxos-api
// Deploy with: supabase functions deploy kyxos-api --no-verify-jwt=false
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const MAX_UPLOAD_BYTES = Number(Deno.env.get('KYXOS_MAX_UPLOAD_BYTES') ?? 536870912);
const ALLOWED_ORIGINS = new Set((Deno.env.get('KYXOS_ALLOWED_ORIGINS') ?? '').split(',').filter(Boolean));
const mimeByExtension: Record<string, string[]> = { glb: ['model/gltf-binary', 'application/octet-stream'], hdr: ['image/vnd.radiance', 'application/octet-stream'], exr: ['image/x-exr', 'application/octet-stream'], png: ['image/png'], jpg: ['image/jpeg'], jpeg: ['image/jpeg'], webp: ['image/webp'], ktx2: ['image/ktx2', 'application/octet-stream'] };
function cors(request: Request) { const origin = request.headers.get('origin') ?? ''; return { 'access-control-allow-origin': ALLOWED_ORIGINS.has(origin) ? origin : '', 'access-control-allow-headers': 'authorization, apikey, content-type', 'access-control-allow-methods': 'GET,POST,PUT,PATCH,DELETE,OPTIONS', vary: 'origin' } }
function json(request: Request, data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: { ...cors(request), 'content-type': 'application/json', 'cache-control': 'no-store' } }) }
function publicJson(request: Request, data: unknown, status = 200) { return new Response(JSON.stringify(data), { status, headers: { ...cors(request), 'content-type': 'application/json', 'cache-control': 'public, max-age=60, stale-while-revalidate=300' } }) }
function safeName(name: string) { return name.normalize('NFKC').replace(/[^\w. -]/g, '_').replace(/\.+/g, '.').slice(0, 180) }
function validHash(hash: string) { return /^[a-f0-9]{64}$/.test(hash) }
function extension(name: string) { return name.split('.').pop()?.toLowerCase() ?? '' }
function prefixMatches(bytes: Uint8Array, signature: number[]) { return signature.every((value, index) => bytes[index] === value) }
function validateHeader(ext: string, bytes: Uint8Array): boolean {
  if (ext === 'glb') return prefixMatches(bytes, [0x67, 0x6c, 0x54, 0x46]);
  if (ext === 'png') return prefixMatches(bytes, [0x89, 0x50, 0x4e, 0x47]);
  if (ext === 'jpg' || ext === 'jpeg') return prefixMatches(bytes, [0xff, 0xd8, 0xff]);
  if (ext === 'webp') return new TextDecoder().decode(bytes.slice(0, 4)) === 'RIFF' && new TextDecoder().decode(bytes.slice(8, 12)) === 'WEBP';
  if (ext === 'ktx2') return prefixMatches(bytes, [0xab, 0x4b, 0x54, 0x58, 0x20, 0x32, 0x30, 0xbb]);
  if (ext === 'exr') return prefixMatches(bytes, [0x76, 0x2f, 0x31, 0x01]);
  if (ext === 'hdr') return new TextDecoder().decode(bytes.slice(0, 10)).startsWith('#?RADIANCE');
  return false;
}
async function digest(scene: unknown) { const data = new TextEncoder().encode(JSON.stringify(scene)); const bytes = await crypto.subtle.digest('SHA-256', data); return [...new Uint8Array(bytes)].map((value) => value.toString(16).padStart(2, '0')).join('') }
function sceneAssetHashes(scene: any): string[] { return Object.values(scene?.assets ?? {}).map((asset: any) => String(asset.contentHash)) }
function assertSafeContract(scene: any) { const text = JSON.stringify(scene); if (/<script|javascript:|onerror\s*=|onload\s*=/i.test(text)) throw new Error('Executable content is forbidden.'); if (/service[_-]?role|jwt[_-]?secret|access[_-]?token/i.test(text)) throw new Error('Secrets are forbidden.'); for (const asset of Object.values(scene?.assets ?? {}) as any[]) if (!String(asset.uri).startsWith('asset://') || /https?:|token=|signature=/i.test(String(asset.uri))) throw new Error('Scene assets must use asset:// content hashes.') }

Deno.serve(async (request) => {
  if (request.method === 'OPTIONS') return new Response(null, { status: 204, headers: cors(request) });
  const url = new URL(request.url); const path = url.pathname.replace(/^.*\/kyxos-api\/?/, '');
  const authHeader = request.headers.get('authorization') ?? ''; const userClient = createClient(SUPABASE_URL, ANON_KEY, { global: { headers: { authorization: authHeader } } }); const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);
  const { data: { user } } = await userClient.auth.getUser();
  try {
    if (path.startsWith('public/')) {
      const [kind, value] = path.slice(7).split('/'); let version: any = null;
      if (kind === 'version') { const { data, error } = await admin.from('published_versions').select('*,public_slugs!inner(slug,is_enabled)').eq('id', value).eq('public_slugs.is_enabled', true).single(); if (error) throw error; version = data }
      else if (kind === 'slug') { const { data: slugRow, error } = await admin.from('public_slugs').select('current_version_id').eq('slug', value).eq('is_enabled', true).single(); if (error) throw error; const { data } = await admin.from('published_versions').select('*').eq('id', slugRow.current_version_id).single(); version = data }
      else return publicJson(request, { error: 'not found' }, 404);
      return publicJson(request, { id: version.id, projectId: version.project_id, versionNumber: version.version_number, sceneSnapshot: version.scene_snapshot, sceneDigest: version.scene_digest, slug: version.public_slugs?.[0]?.slug ?? '', createdAt: version.created_at, isCurrent: true });
    }
    if (!user) return json(request, { error: 'authentication required' }, 401);
    if (path === 'projects' && request.method === 'GET') { const { data, error } = await userClient.from('projects').select('*').eq('status', 'active').order('updated_at', { ascending: false }); if (error) throw error; return json(request, data.map((row: any) => ({ id: row.id, name: row.name, description: row.description, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at }))) }
    if (path === 'projects' && request.method === 'POST') { const body = await request.json(); const { data, error } = await userClient.from('projects').insert({ owner_id: user.id, name: safeName(String(body.name ?? 'Untitled Project')) }).select().single(); if (error) throw error; await userClient.from('project_members').insert({ project_id: data.id, user_id: user.id, role: 'owner' }); return json(request, { id: data.id, name: data.name, status: data.status, createdAt: data.created_at, updatedAt: data.updated_at }, 201) }
    const projectMatch = path.match(/^projects\/([0-9a-f-]+)(?:\/(duplicate))?$/i);
    if (projectMatch) {
      const id = projectMatch[1]; if (projectMatch[2] && request.method === 'POST') { const { data: source, error } = await userClient.from('projects').select('*').eq('id', id).single(); if (error) throw error; const { data: copy, error: copyError } = await userClient.from('projects').insert({ owner_id: user.id, name: `${source.name} Copy`, description: source.description }).select().single(); if (copyError) throw copyError; const { data: draft } = await userClient.from('scene_drafts').select('*').eq('project_id', id).maybeSingle(); if (draft) await userClient.rpc('save_scene_draft', { target_project: copy.id, expected_revision: 0, contract: draft.contract_json, contract_version_value: draft.contract_version }); return json(request, { id: copy.id, name: copy.name, status: copy.status, createdAt: copy.created_at, updatedAt: copy.updated_at }) }
      if (request.method === 'GET') { const { data, error } = await userClient.from('projects').select('*').eq('id', id).single(); if (error) throw error; return json(request, { id: data.id, name: data.name, description: data.description, status: data.status, createdAt: data.created_at, updatedAt: data.updated_at }) }
      if (request.method === 'PATCH') { const body = await request.json(); const patch: any = {}; if (body.name != null) patch.name = safeName(String(body.name)); if (body.status === 'archived') patch.status = 'archived'; const { error } = await userClient.from('projects').update(patch).eq('id', id); if (error) throw error; return json(request, { ok: true }) }
      if (request.method === 'DELETE') { const { count } = await userClient.from('published_versions').select('*', { count: 'exact', head: true }).eq('project_id', id); if (count) return json(request, { error: 'published projects cannot be deleted' }, 409); const { error } = await userClient.from('projects').delete().eq('id', id); if (error) throw error; return json(request, { ok: true }) }
    }
    const draftMatch = path.match(/^drafts\/([0-9a-f-]+)(?:\/(revision))?$/i);
    if (draftMatch) { const projectId = draftMatch[1]; if (draftMatch[2]) { const { data } = await userClient.from('scene_drafts').select('revision').eq('project_id', projectId).maybeSingle(); return json(request, { revision: data?.revision ?? 0 }) } if (request.method === 'GET') { const { data, error } = await userClient.from('scene_drafts').select('*').eq('project_id', projectId).maybeSingle(); if (error) throw error; return json(request, data ? { projectId, contract: data.contract_json, revision: data.revision, updatedAt: data.updated_at } : null) } if (request.method === 'PUT') { const body = await request.json(); assertSafeContract(body.contract); const { data, error } = await userClient.rpc('save_scene_draft', { target_project: projectId, expected_revision: body.expectedRevision, contract: body.contract, contract_version_value: body.contract.contractVersion }); if (error) throw error; return json(request, { revision: data }) } }
    if (path === 'assets/upload' && request.method === 'POST') { const body = await request.json(); const name = safeName(String(body.name ?? 'asset')); const ext = extension(name); const mime = String(body.mimeType ?? 'application/octet-stream'); const size = Number(body.byteSize); const hash = String(body.hash ?? ''); if (!validHash(hash) || !mimeByExtension[ext]?.includes(mime) || !Number.isSafeInteger(size) || size <= 0 || size > MAX_UPLOAD_BYTES) return json(request, { error: 'invalid upload metadata' }, 400); const { data: existing } = await userClient.from('assets').select('*').eq('content_hash', hash).maybeSingle(); if (existing) return json(request, { assetId: existing.id, storageKey: existing.storage_key, alreadyExists: true }); const storageKey = `${user.id}/${hash}/${name}`; const { data: asset, error } = await userClient.from('assets').insert({ owner_id: user.id, content_hash: hash, storage_key: storageKey, mime_type: mime, byte_size: size }).select().single(); if (error) throw error; const { data: signed, error: signedError } = await admin.storage.from('kyxos-assets').createSignedUploadUrl(storageKey); if (signedError) throw signedError; return json(request, { assetId: asset.id, storageKey, uploadUrl: signed.signedUrl, headers: {} }, 201) }
    if (path === 'assets/complete' && request.method === 'POST') { const body = await request.json(); const { data: asset, error } = await userClient.from('assets').select('*').eq('id', body.assetId).single(); if (error) throw error; const { data: blob, error: downloadError } = await admin.storage.from('kyxos-assets').download(asset.storage_key); if (downloadError) throw downloadError; if (blob.size !== asset.byte_size) throw new Error('uploaded byte size does not match'); const bytes = new Uint8Array(await blob.slice(0, 16).arrayBuffer()); if (!validateHeader(extension(asset.storage_key), bytes)) throw new Error('file header does not match its extension'); const computed = await crypto.subtle.digest('SHA-256', await blob.arrayBuffer()); const computedHash = [...new Uint8Array(computed)].map((value) => value.toString(16).padStart(2, '0')).join(''); if (computedHash !== asset.content_hash) throw new Error('content hash mismatch'); await userClient.from('assets').update({ metadata_json: body.metadata ?? {} }).eq('id', asset.id); return json(request, { ok: true }) }
    if (path === 'assets/manifest' && request.method === 'POST') { const body = await request.json(); const ids = Array.isArray(body.assetIds) ? body.assetIds.slice(0, 500) : []; const { data, error } = await userClient.from('assets').select('*').in('id', ids); if (error) throw error; const assets: Record<string, string> = {}; for (const asset of data) { const { data: signed } = await admin.storage.from('kyxos-assets').createSignedUrl(asset.storage_key, 900); if (signed) assets[`asset://${asset.content_hash}`] = signed.signedUrl } return json(request, { assets }) }
    if (path === 'releases/publish' && request.method === 'POST') { const body = await request.json(); assertSafeContract(body.contract); const hashes = sceneAssetHashes(body.contract); const { data: assets, error: assetError } = await userClient.from('assets').select('id,content_hash').in('content_hash', hashes); if (assetError) throw assetError; if (assets.length !== new Set(hashes).size) throw new Error('one or more assets are missing'); const { data: project } = await userClient.from('projects').select('name').eq('id', body.projectId).single(); const slugValue = `${String(project.name).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40) || 'scene'}-${body.projectId.slice(0, 8)}`; const sceneDigest = await digest(body.contract); const { data: release, error } = await userClient.rpc('publish_scene', { target_project: body.projectId, expected_revision: body.expectedRevision, snapshot: body.contract, digest: sceneDigest, contract_version_value: body.contract.contractVersion, compatibility: body.contract.compatibility, asset_ids: assets.map((entry: any) => entry.id), slug_value: slugValue }); if (error) throw error; return json(request, { id: release.id, projectId: release.project_id, versionNumber: release.version_number, sceneSnapshot: release.scene_snapshot, sceneDigest: release.scene_digest, slug: slugValue, createdAt: release.created_at, isCurrent: true }, 201) }
    if (path.startsWith('releases') && request.method === 'GET') { const projectId = url.searchParams.get('projectId'); const { data, error } = await userClient.from('published_versions').select('*,public_slugs(slug,current_version_id)').eq('project_id', projectId).order('version_number', { ascending: false }); if (error) throw error; return json(request, data.map((release: any) => ({ id: release.id, projectId: release.project_id, versionNumber: release.version_number, sceneSnapshot: release.scene_snapshot, sceneDigest: release.scene_digest, slug: release.public_slugs?.[0]?.slug ?? '', createdAt: release.created_at, isCurrent: release.public_slugs?.[0]?.current_version_id === release.id }))) }
    if (path === 'releases/current' && request.method === 'POST') { const body = await request.json(); const { error } = await userClient.from('public_slugs').update({ current_version_id: body.versionId, is_enabled: true }).eq('project_id', body.projectId); if (error) throw error; return json(request, { ok: true }) }
    if (path === 'releases/disable' && request.method === 'POST') { const body = await request.json(); const { error } = await userClient.from('public_slugs').update({ is_enabled: false }).eq('project_id', body.projectId); if (error) throw error; return json(request, { ok: true }) }
    return json(request, { error: 'not found' }, 404);
  } catch (error) { console.error(error); const message = error instanceof Error ? error.message : String(error); const status = /forbidden/i.test(message) ? 403 : /conflict|40001/i.test(message) ? 409 : /not found|PGRST116/i.test(message) ? 404 : 400; return json(request, { error: message.replace(/storage_key|service_role|stack/gi, '[redacted]') }, status) }
});
