export const MIXED_VALUE = Symbol('KyxosMixedValue');
export type InspectorFieldType = 'string'|'number'|'boolean'|'color'|'vector2'|'vector3'|'vector4'|'enum'|'asset'|'entity'|'texture'|'material';
export interface InspectorFieldSchema { path:string; label:string; type:InspectorFieldType; group?:string; description?:string; unit?:string; min?:number; max?:number; step?:number; options?:Array<{label:string;value:string|number}>; assetTypes?:string[]; nullable?:boolean; defaultValue?:unknown; }
export interface InspectorSectionSchema { id:string; label:string; fields:InspectorFieldSchema[] }
export interface InspectorSchema { id:string; sections:InspectorSectionSchema[] }
const parts=(path:string)=>path.replace(/^\//,'').split('/').filter(Boolean).map((p)=>p.replace(/~1/g,'/').replace(/~0/g,'~'));
export function readInspectorValue(target:unknown,path:string):unknown { let value:any=target; for(const part of parts(path)) value=value?.[Array.isArray(value)?Number(part):part]; return value; }
export function writeInspectorValue<T>(target:T,path:string,value:unknown):T { const output:any=structuredClone(target); const ps=parts(path); let cursor=output; for(const part of ps.slice(0,-1)){const key=Array.isArray(cursor)?Number(part):part; cursor[key]??={}; cursor=cursor[key];} const last=ps.at(-1); if(last==null)return structuredClone(value) as T; cursor[Array.isArray(cursor)?Number(last):last]=structuredClone(value); return output; }
export function mixedInspectorValue(targets:unknown[],path:string):unknown|typeof MIXED_VALUE { if(!targets.length)return undefined; const first=readInspectorValue(targets[0],path); return targets.slice(1).every((target)=>JSON.stringify(readInspectorValue(target,path))===JSON.stringify(first))?structuredClone(first):MIXED_VALUE; }
export function validateInspectorValue(field:InspectorFieldSchema,value:unknown):string[] { const errors:string[]=[]; if(value==null&&!field.nullable)errors.push(`${field.label} is required.`); if(typeof value==='number'){if(field.min!=null&&value<field.min)errors.push(`${field.label} must be at least ${field.min}${field.unit??''}.`); if(field.max!=null&&value>field.max)errors.push(`${field.label} must be at most ${field.max}${field.unit??''}.`);} return errors; }
export interface OverrideRecord { path:string;baseValue:unknown;value:unknown }
export class OverrideStore { private records=new Map<string,OverrideRecord>(); set(path:string,baseValue:unknown,value:unknown){this.records.set(path,{path,baseValue:structuredClone(baseValue),value:structuredClone(value)});} has(path:string){return this.records.has(path);} get(path:string){const r=this.records.get(path);return r?structuredClone(r):null;} reset(path:string){const r=this.records.get(path);if(!r)return undefined;this.records.delete(path);return structuredClone(r.baseValue);} restore(path:string){return this.reset(path);} apply(path:string,base:unknown){const r=this.records.get(path);return structuredClone(r?r.value:base);} list(){return[...this.records.values()].map((r)=>structuredClone(r));} }
export const nodeInspectorSchema:InspectorSchema={id:'node',sections:[{id:'transform',label:'Transform',fields:[{path:'/name',label:'Name',type:'string'},{path:'/transform/position',label:'Position',type:'vector3',unit:'m',step:.01},{path:'/transform/rotation',label:'Rotation',type:'vector3',unit:'°',step:.1},{path:'/transform/scale',label:'Scale',type:'vector3',min:.0001,step:.01},{path:'/visible',label:'Visible',type:'boolean',defaultValue:true}]},{id:'render',label:'Rendering',fields:[{path:'/castShadow',label:'Cast Shadows',type:'boolean',defaultValue:true},{path:'/receiveShadow',label:'Receive Shadows',type:'boolean',defaultValue:true},{path:'/materialId',label:'Material',type:'material',nullable:true,assetTypes:['material']}]}]};
export const materialInspectorSchema:InspectorSchema={id:'material',sections:[{id:'surface',label:'Surface',fields:[{path:'/baseColor',label:'Base Color',type:'color'},{path:'/baseColorTexture',label:'Base Color Texture',type:'texture',nullable:true,assetTypes:['texture']},{path:'/metalness',label:'Metalness',type:'number',min:0,max:1,step:.01},{path:'/roughness',label:'Roughness',type:'number',min:0,max:1,step:.01},{path:'/normalTexture',label:'Normal Texture',type:'texture',nullable:true,assetTypes:['texture']},{path:'/emissive',label:'Emissive',type:'color'},{path:'/opacity',label:'Opacity',type:'number',min:0,max:1,step:.01},{path:'/alphaMode',label:'Alpha Mode',type:'enum',options:[{label:'Opaque',value:'OPAQUE'},{label:'Mask',value:'MASK'},{label:'Blend',value:'BLEND'}]},{path:'/doubleSided',label:'Double Sided',type:'boolean'}]}]};
export const cameraInspectorSchema:InspectorSchema={id:'camera',sections:[{id:'camera',label:'Camera',fields:[{path:'/camera/projection',label:'Projection',type:'enum',options:[{label:'Perspective',value:'perspective'},{label:'Orthographic',value:'orthographic'}]},{path:'/camera/fov',label:'Field of View',type:'number',unit:'°',min:1,max:179,step:.1},{path:'/camera/near',label:'Near Clip',type:'number',unit:'m',min:.0001,step:.001},{path:'/camera/far',label:'Far Clip',type:'number',unit:'m',min:.001,step:1},{path:'/camera/exposure',label:'Exposure',type:'number',min:0,max:20,step:.01}]}]};
export const lightInspectorSchema:InspectorSchema={id:'light',sections:[{id:'light',label:'Light',fields:[{path:'/light/type',label:'Type',type:'enum',options:[{label:'Directional',value:'directional'},{label:'Point',value:'point'},{label:'Spot',value:'spot'}]},{path:'/light/color',label:'Color',type:'color'},{path:'/light/intensity',label:'Intensity',type:'number',min:0,step:.01},{path:'/light/range',label:'Range',type:'number',unit:'m',min:0,step:.1},{path:'/light/castShadow',label:'Cast Shadows',type:'boolean'},{path:'/light/shadowBias',label:'Shadow Bias',type:'number',min:-.1,max:.1,step:.0001}]}]};
export const renderInspectorSchema:InspectorSchema={id:'render',sections:[{id:'render',label:'Render Settings',fields:[{path:'/quality',label:'Quality',type:'enum',options:[{label:'Low',value:'low'},{label:'Medium',value:'medium'},{label:'High',value:'high'},{label:'Cinematic',value:'cinematic'}]},{path:'/toneMapping',label:'Tone Mapping',type:'enum',options:[{label:'ACES',value:'aces'},{label:'Neutral',value:'neutral'},{label:'None',value:'none'}]},{path:'/exposure',label:'Exposure',type:'number',min:0,max:20,step:.01},{path:'/ssgi/enabled',label:'SSGI',type:'boolean'},{path:'/ssr/enabled',label:'SSR',type:'boolean'},{path:'/traa/enabled',label:'TRAA',type:'boolean'},{path:'/bloom/enabled',label:'Bloom',type:'boolean'},{path:'/depthOfField/enabled',label:'Depth of Field',type:'boolean'}]}]};