export type AssetKind='folder'|'model'|'texture'|'material'|'animation'|'environment'|'script'|'other'; export type ImportState='queued'|'reading'|'decoding'|'processing'|'uploading'|'complete'|'failed'|'cancelled';
export interface WorkspaceAsset{id:string;name:string;kind:AssetKind;parentId:string|null;mimeType?:string;hash?:string;thumbnailUrl?:string;deletedAt?:string|null;dependencies?:string[];sourceAssetId?:string;metadata?:Record<string,unknown>;createdAt:string;updatedAt:string}
export interface AssetFilter{query?:string;kinds?:AssetKind[];parentId?:string|null;includeDeleted?:boolean} export interface ImportTask{id:string;fileName:string;state:ImportState;progress:number;error?:string;assetId?:string;startedAt?:string;completedAt?:string}
const now=()=>new Date().toISOString(); const clone=<T>(v:T):T=>structuredClone(v);
export class AssetWorkspace extends EventTarget{private assets=new Map<string,WorkspaceAsset>();private tasks=new Map<string,ImportTask>();
addFolder(name:string,parentId:string|null=null,id=crypto.randomUUID()){return this.add({id,name,kind:'folder',parentId,createdAt:now(),updatedAt:now()});}
add(asset:WorkspaceAsset){if(this.assets.has(asset.id))throw new Error(`Asset already exists: ${asset.id}`);this.assertParent(asset.parentId);this.assets.set(asset.id,clone(asset));this.emit();return clone(asset);} get(id:string){const a=this.assets.get(id);return a?clone(a):null;}
list(filter:AssetFilter={}){const q=filter.query?.trim().toLowerCase();return[...this.assets.values()].filter(a=>{if(!filter.includeDeleted&&a.deletedAt)return false;if(filter.parentId!==undefined&&a.parentId!==filter.parentId)return false;if(filter.kinds?.length&&!filter.kinds.includes(a.kind))return false;return !q||`${a.name} ${a.kind} ${a.mimeType??''}`.toLowerCase().includes(q);}).sort((a,b)=>Number(b.kind==='folder')-Number(a.kind==='folder')||a.name.localeCompare(b.name)).map(clone);}
rename(id:string,name:string){const a=this.require(id);a.name=name.trim()||a.name;a.updatedAt=now();this.emit();} move(id:string,parentId:string|null){const a=this.require(id);this.assertParent(parentId);if(id===parentId||this.isDescendant(parentId,id))throw new Error('Cannot move an asset into itself or its descendant.');a.parentId=parentId;a.updatedAt=now();this.emit();}
delete(id:string){const t=now();for(const a of this.descendantsInclusive(id)){a.deletedAt=t;a.updatedAt=t;}this.emit();} restore(id:string){for(const a of this.descendantsInclusive(id)){a.deletedAt=null;a.updatedAt=now();}this.emit();} purge(id:string){for(const a of this.descendantsInclusive(id))this.assets.delete(a.id);this.emit();}
dependencies(id:string){return(this.require(id).dependencies??[]).map(x=>this.assets.get(x)).filter(Boolean).map(a=>clone(a!));} references(id:string){return[...this.assets.values()].filter(a=>a.dependencies?.includes(id)).map(clone);}
preserveOverridesOnReimport(id:string,replacement:Omit<WorkspaceAsset,'id'|'createdAt'|'updatedAt'>){const current=this.require(id);const overrides=clone(current.metadata?.overrides??{});const next:WorkspaceAsset={...clone(replacement),id,createdAt:current.createdAt,updatedAt:now(),metadata:{...(replacement.metadata??{}),overrides}};this.assets.set(id,next);this.emit();return clone(next);}
enqueue(fileName:string,id=crypto.randomUUID()){const task:ImportTask={id,fileName,state:'queued',progress:0};this.tasks.set(id,task);this.emitTask(task);return clone(task);} updateTask(id:string,state:ImportState,progress:number,error?:string,assetId?:string){const t=this.tasks.get(id);if(!t)throw new Error(`Unknown import task: ${id}`);const allowed:Record<ImportState,ImportState[]>={queued:['reading','cancelled'],reading:['decoding','failed','cancelled'],decoding:['processing','failed','cancelled'],processing:['uploading','complete','failed','cancelled'],uploading:['complete','failed','cancelled'],complete:[],failed:['queued'],cancelled:['queued']};if(t.state!==state&&!allowed[t.state].includes(state))throw new Error(`Invalid import transition ${t.state} -> ${state}`);t.state=state;t.progress=Math.max(0,Math.min(1,progress));t.error=error;t.assetId=assetId??t.assetId;t.startedAt??=state==='queued'?undefined:now();if(['complete','failed','cancelled'].includes(state))t.completedAt=now();this.emitTask(t);} listTasks(){return[...this.tasks.values()].map(clone);} retryTask(id:string){const t=this.tasks.get(id);if(!t||!['failed','cancelled'].includes(t.state))throw new Error('Only failed or cancelled tasks can be retried.');this.updateTask(id,'queued',0);}
private require(id:string){const a=this.assets.get(id);if(!a)throw new Error(`Unknown asset: ${id}`);return a;}private assertParent(id:string|null){if(id!=null&&this.require(id).kind!=='folder')throw new Error('Asset parent must be a folder.');}private isDescendant(candidate:string|null,ancestor:string){let c=candidate?this.assets.get(candidate):undefined;while(c){if(c.id===ancestor)return true;c=c.parentId?this.assets.get(c.parentId):undefined;}return false;}private descendantsInclusive(id:string){const out:WorkspaceAsset[]=[];const visit=(x:string)=>{const a=this.require(x);out.push(a);for(const c of this.assets.values())if(c.parentId===x)visit(c.id);};visit(id);return out;}private emit(){this.dispatchEvent(new CustomEvent('change',{detail:{assets:this.list({includeDeleted:true})}}));}private emitTask(task:ImportTask){this.dispatchEvent(new CustomEvent('task',{detail:clone(task)}));}}
