import './styles.css';
import { assetResolverFromManifest, createApiClient, hashBlob, type AssetManifest, type KyxosApiClient, type ProjectSummary } from '@kyxos/api-client';
import { AutosaveController, ProjectSession, SceneDocument, replaceCommand, type OfflineDraftStore } from '@kyxos/editor-core';
import { createEmptySceneContract, type KyxosSceneContract, type SceneMaterial, type SceneNode } from '@kyxos/scene-contract';
import { button, element, safeText, setBusy } from '@kyxos/shared-ui';
import { createStudioShell } from '@kyxos/studio-shell';
import { BrowserKyxosViewportAdapter } from '@kyxos/viewer-adapter';

const app = document.querySelector<HTMLElement>('#app')!;
const client = createApiClient({ url: import.meta.env.VITE_SUPABASE_URL, anonKey: import.meta.env.VITE_SUPABASE_ANON_KEY, functionsUrl: import.meta.env.VITE_KYXOS_FUNCTIONS_URL });
const offlineStore: OfflineDraftStore = {
  async put(projectId, draft) { localStorage.setItem(`kyxos-offline:${projectId}`, JSON.stringify(draft)) },
  async get(projectId) { const raw = localStorage.getItem(`kyxos-offline:${projectId}`); return raw ? JSON.parse(raw) : null },
  async delete(projectId) { localStorage.removeItem(`kyxos-offline:${projectId}`) },
};

async function boot(): Promise<void> { (await client.auth.getSession()) ? await renderProjects() : renderLogin() }

function renderLogin(): void {
  const panel = element('form', { className: 'auth-card' });
  panel.innerHTML = '<div class="brand-mark">K</div><h1>Kyxos Studio</h1><p>Sign in to create, edit and publish immutable 3D scenes.</p><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Password<input name="password" type="password" required autocomplete="current-password"></label><button type="submit">Sign in</button><small>Without Supabase environment variables, the Pages preview uses the local owner-only provider.</small><div class="form-error" role="alert"></div>';
  panel.addEventListener('submit', async (event) => { event.preventDefault(); const submit = panel.querySelector('button')!; setBusy(submit, true); try { const data = new FormData(panel); await client.auth.signIn(String(data.get('email')), String(data.get('password'))); await renderProjects() } catch (error) { panel.querySelector('.form-error')!.textContent = error instanceof Error ? error.message : String(error) } finally { setBusy(submit, false) } });
  app.replaceChildren(element('main', { className: 'auth-screen' })); app.firstElementChild!.append(panel);
}

async function renderProjects(): Promise<void> {
  const screen = element('main', { className: 'projects-screen' }); const header = element('header', { className: 'projects-header' }); header.innerHTML = '<div><span class="brand-mark small">K</span><strong>Kyxos Studio</strong></div>';
  const actions = element('div', { className: 'project-actions' }); const create = button('New project', async () => { const name = prompt('Project name', 'Untitled Project'); if (!name) return; const project = await client.projects.create(name); await openProject(project) }); actions.append(create, button('Sign out', async () => { await client.auth.signOut(); renderLogin() }, 'secondary')); header.append(actions);
  const grid = element('section', { className: 'project-grid' }); const projects = await client.projects.list();
  if (!projects.length) grid.append(element('div', { className: 'empty-state', text: 'Create a project, upload a GLB, edit it, and publish an immutable version.' }));
  for (const project of projects) {
    const card = element('article', { className: 'project-card' }); card.innerHTML = `<div class="project-thumb">3D</div><div class="project-copy"><h2>${safeText(project.name)}</h2><p>Updated ${new Date(project.updatedAt).toLocaleString()}</p></div>`;
    card.tabIndex = 0; card.addEventListener('click', () => void openProject(project)); card.addEventListener('keydown', (event) => { if (event.key === 'Enter') void openProject(project) });
    const menu = button('•••', () => { const action = prompt('Action: rename, duplicate, archive, delete'); void handleProjectAction(project, action ?? '') }, 'icon-button'); menu.addEventListener('click', (event) => event.stopPropagation()); card.append(menu); grid.append(card);
  }
  screen.append(header, element('div', { className: 'projects-title', text: 'Projects' }), grid); app.replaceChildren(screen);
}
async function handleProjectAction(project: ProjectSummary, action: string) { if (action === 'rename') { const name = prompt('New name', project.name); if (name) await client.projects.rename(project.id, name) } else if (action === 'duplicate') await client.projects.duplicate(project.id); else if (action === 'archive') await client.projects.archive(project.id); else if (action === 'delete') await client.projects.remove(project.id); await renderProjects() }

async function openProject(project: ProjectSummary): Promise<void> {
  const draft = await client.drafts.load(project.id); const document = new SceneDocument(draft?.contract ?? createEmptySceneContract(project.name)); const session = new ProjectSession(project.id, document);
  let manifest: AssetManifest = await client.assets.getManifest(Object.keys(document.value.assets));
  const resolver = { resolve(asset: any) { const url = manifest.assets[asset.uri]; if (!url) throw new Error(`Asset is not available: ${asset.uri}`); return url } };
  const shell = createStudioShell(app); const canvas = element('canvas', { attrs: { id: 'studio-canvas', tabindex: '0' } }); const overlay = element('div', { className: 'viewport-overlay' }); shell.viewport.append(canvas, overlay);
  const adapter = new BrowserKyxosViewportAdapter(resolver); await adapter.mount(canvas); await adapter.loadDocument(document); const unbind = adapter.bindSession(session);
  const autosave = new AutosaveController(project.id, document, { save: (id, contract, revision) => client.drafts.save(id, contract, revision), load: async (id) => { const value = await client.drafts.load(id); return value ? { contract: value.contract, revision: value.revision } : null } }, offlineStore, draft?.revision ?? 0);
  const saveBadge = element('span', { className: 'save-state', text: autosave.state }); autosave.addEventListener('state', (event) => { saveBadge.textContent = (event as CustomEvent).detail.state; saveBadge.dataset.state = (event as CustomEvent).detail.state });
  shell.topbar.append(button('← Projects', async () => { await autosave.flush(); unbind(); adapter.dispose(); autosave.dispose(); await renderProjects() }, 'secondary'), element('strong', { text: project.name }), saveBadge);
  const toolGroup = element('div', { className: 'tool-group' }); for (const [label, tool] of [['Select', 'select'], ['Move', 'translate'], ['Rotate', 'rotate'], ['Scale', 'scale']] as const) toolGroup.append(button(label, () => { adapter.setTool(tool); [...toolGroup.children].forEach((child) => child.classList.toggle('active', child.textContent === label)) }, tool === 'select' ? 'active' : '')); shell.topbar.append(toolGroup);
  shell.topbar.append(button('Undo', () => session.history.undo()), button('Redo', () => session.history.redo()), button('Preview', () => window.open('../public/?draft=1', '_blank'), 'secondary'));
  const upload = element('input', { attrs: { type: 'file', accept: '.glb,.hdr,.exr,.png,.jpg,.jpeg,.webp,.ktx2', hidden: '' } }); upload.addEventListener('change', () => { const file = upload.files?.[0]; if (file) void importAsset(file) }); shell.topbar.append(upload, button('Upload', () => upload.click()), button('Publish', () => void publish(), 'primary'));
  const hierarchySearch = element('input', { attrs: { type: 'search', placeholder: 'Search hierarchy' } }); shell.hierarchy.append(element('h2', { text: 'Hierarchy' }), hierarchySearch); const tree = element('div', { className: 'hierarchy-tree' }); shell.hierarchy.append(tree);
  hierarchySearch.addEventListener('input', () => renderHierarchy(hierarchySearch.value));
  adapter.addEventListener('selection', (event) => session.selection.select((event as CustomEvent<{ nodeIds: string[] }>).detail.nodeIds)); session.selection.addEventListener('change', () => { renderHierarchy(hierarchySearch.value); renderInspector() });
  session.document.addEventListener('change', () => { renderHierarchy(hierarchySearch.value); renderInspector(); renderAssets() });
  const shortcuts = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); event.shiftKey ? session.history.redo() : session.history.undo() } else if (event.key.toLowerCase() === 'f' && session.selection.selected[0]) adapter.frame(session.selection.selected) };
  window.addEventListener('keydown', shortcuts); window.addEventListener('beforeunload', () => void autosave.flush(), { once: true });

  function renderHierarchy(query = ''): void {
    tree.replaceChildren(); const scene = document.value; const normalized = query.trim().toLowerCase();
    for (const [index, node] of scene.nodes.entries()) {
      if (normalized && !node.name.toLowerCase().includes(normalized)) continue;
      const row = element('div', { className: 'hierarchy-row', attrs: { draggable: 'true', 'data-node': node.id } }); row.style.paddingLeft = `${12 + depth(scene.nodes, node) * 14}px`; row.classList.toggle('selected', session.selection.selected.includes(node.id)); row.classList.toggle('locked', Boolean(node.locked));
      const visibility = button(node.visible ? '◉' : '○', () => session.commands.execute(replaceCommand(`/nodes/${index}/visible`, !node.visible, 'Toggle visibility')), 'mini');
      const name = element('span', { text: node.name }); name.addEventListener('dblclick', () => { const next = prompt('Node name', node.name); if (next) session.commands.execute(replaceCommand(`/nodes/${index}/name`, next, 'Rename node')) });
      const lock = button(node.locked ? '🔒' : '◇', () => session.commands.execute(replaceCommand(`/nodes/${index}/locked`, !node.locked, 'Lock node')), 'mini'); row.append(visibility, name, lock);
      row.addEventListener('click', (event) => session.selection.select([node.id], (event.ctrlKey || event.metaKey) ? 'toggle' : 'replace'));
      row.addEventListener('dragstart', (event) => event.dataTransfer?.setData('text/kyxos-node', node.id)); row.addEventListener('dragover', (event) => event.preventDefault()); row.addEventListener('drop', (event) => { event.preventDefault(); const childId = event.dataTransfer?.getData('text/kyxos-node'); if (childId && childId !== node.id) reparent(childId, node.id) }); tree.append(row);
    }
  }
  function reparent(childId: string, parentId: string) { const scene = document.value; const childIndex = scene.nodes.findIndex((node) => node.id === childId); if (childIndex < 0) return; session.commands.execute(replaceCommand(`/nodes/${childIndex}/parentId`, parentId, 'Reparent node')) }
  function renderInspector(): void {
    shell.inspector.replaceChildren(element('h2', { text: 'Inspector' })); const selectedId = session.selection.selected[0]; const scene = document.value; const index = scene.nodes.findIndex((node) => node.id === selectedId);
    if (index < 0) { renderRenderSettings(); return }
    const node = scene.nodes[index]; shell.inspector.append(element('label', { text: 'Name' })); const name = element('input', { attrs: { value: node.name } }); name.addEventListener('change', () => session.commands.execute(replaceCommand(`/nodes/${index}/name`, name.value, 'Rename node'))); shell.inspector.append(name, element('h3', { text: 'Transform' }));
    for (const property of ['position', 'rotation', 'scale'] as const) { const group = element('fieldset', { className: 'vector-field' }); group.append(element('legend', { text: property[0].toUpperCase() + property.slice(1) })); for (const axis of ['x', 'y', 'z'] as const) { const input = element('input', { attrs: { type: 'number', step: property === 'rotation' ? '0.01' : '0.1', value: String(node.transform[property][axis]), 'aria-label': `${property} ${axis}` } }); input.addEventListener('input', () => session.commands.execute(replaceCommand(`/nodes/${index}/transform/${property}/${axis}`, Number(input.value), `Change ${property}`, `${node.id}:${property}`))); group.append(element('span', { text: axis.toUpperCase() }), input) } shell.inspector.append(group) }
    const materialId = node.materialSlots?.[0]; if (materialId && scene.materials[materialId]) renderMaterial(materialId, scene.materials[materialId]); renderRenderSettings();
  }
  function renderMaterial(id: string, material: SceneMaterial) { const index = `/materials/${escapePointer(id)}`; shell.inspector.append(element('h3', { text: `Material · ${material.name}` })); const color = element('input', { attrs: { type: 'color', value: rgbHex(material.baseColor) } }); color.addEventListener('input', () => { const [x, y, z] = hexRgb(color.value); session.commands.execute({ id: 'material-color', label: 'Base color', mergeKey: `${id}:color`, patch: () => [{ op: 'replace', path: `${index}/baseColor`, value: { x, y, z, w: material.baseColor.w } }] }) }); shell.inspector.append(element('label', { text: 'Base Color' }), color); for (const key of ['metalness', 'roughness', 'opacity'] as const) { const input = element('input', { attrs: { type: 'range', min: '0', max: '1', step: '0.01', value: String(material[key]) } }); input.addEventListener('input', () => session.commands.execute(replaceCommand(`${index}/${key}`, Number(input.value), `Change ${key}`, `${id}:${key}`))); shell.inspector.append(element('label', { text: key }), input) } }
  function renderRenderSettings() { const scene = document.value; shell.inspector.append(element('h3', { text: 'Render Settings' })); const capabilities = adapter.getViewer()?.getCapabilities(); for (const [effect, capability] of Object.entries(capabilities?.effects ?? {})) { const current = scene.renderSettings.effects[effect as keyof typeof scene.renderSettings.effects]; const row = element('label', { className: 'effect-row' }); const checkbox = element('input', { attrs: { type: 'checkbox' } }); checkbox.checked = current?.enabled ?? false; checkbox.disabled = !capability.available; checkbox.addEventListener('change', () => session.commands.execute({ id: `effect:${effect}`, label: `Toggle ${effect}`, patch: () => [{ op: current ? 'replace' : 'add', path: `/renderSettings/effects/${escapePointer(effect)}`, value: { ...(current ?? {}), enabled: checkbox.checked } }] })); row.append(checkbox, element('span', { text: effect })); shell.inspector.append(row) } }
  function renderAssets() { shell.assets.replaceChildren(); const scene = document.value; const tabs = element('div', { className: 'asset-tabs' }); tabs.append(element('strong', { text: 'Assets' }), element('span', { text: `${Object.keys(scene.assets).length} files` }), element('strong', { text: 'Animation' }), element('span', { text: `${scene.animations.length} clips` })); shell.assets.append(tabs); for (const asset of Object.values(scene.assets)) shell.assets.append(element('div', { className: 'asset-chip', text: `${asset.kind} · ${asset.name ?? asset.contentHash.slice(0, 8)}` })); for (const animation of scene.animations) { const play = button(animation.autoplay ? 'Pause' : 'Play', () => adapter.getViewer()?.setAnimationState({ clipId: animation.id, playing: !animation.autoplay, loop: animation.loop, speed: animation.speed })); const row = element('div', { className: 'animation-chip' }); row.append(play, element('span', { text: animation.name })); shell.assets.append(row) } }
  async function importAsset(file: File) {
    if (file.size > 512 * 1024 * 1024) return alert('File exceeds the configured 512 MB upload limit.'); const extension = file.name.split('.').pop()?.toLowerCase(); if (!['glb', 'hdr', 'exr', 'png', 'jpg', 'jpeg', 'webp', 'ktx2'].includes(extension ?? '')) return alert('Unsupported file type.');
    overlay.textContent = `Hashing ${file.name}…`; const hash = await hashBlob(file); const ticket = await client.assets.createUpload({ hash, name: file.name, mimeType: file.type || mimeFor(extension ?? ''), byteSize: file.size }); await client.assets.upload(ticket, file); await client.assets.completeUpload(ticket.assetId, { originalName: file.name }); manifest = await client.assets.getManifest([ticket.assetId]);
    if (extension === 'glb') { overlay.textContent = 'Parsing GLB in worker…'; const report = await parseGlb(file); const contract = contractFromGlb(project.name, ticket.assetId, hash, file, report); document.replace(contract, 'import-glb'); await adapter.loadDocument(document); overlay.textContent = report.warnings.length ? report.warnings.join(' · ') : 'Import complete'; await autosave.flush() }
    else { const scene = document.value; const kind = ['hdr', 'exr'].includes(extension ?? '') ? 'environment' : 'texture'; scene.assets[ticket.assetId] = { id: ticket.assetId, uri: `asset://${hash}`, contentHash: hash, kind, mimeType: file.type || mimeFor(extension ?? ''), byteSize: file.size, name: file.name }; if (kind === 'environment') scene.environment.assetId = ticket.assetId; document.replace(scene, 'import-asset'); await adapter.loadDocument(document); overlay.textContent = 'Asset uploaded' }
    setTimeout(() => { overlay.textContent = '' }, 3000);
  }
  async function publish() { try { overlay.textContent = 'Saving and publishing…'; await autosave.flush(); const thumbnail = await adapter.captureThumbnail(); const release = await client.releases.publish(project.id, document.value, autosave.revision, thumbnail); const url = new URL(`../public/?release=${encodeURIComponent(release.id)}`, location.href).href; const embed = new URL(`../embed/?release=${encodeURIComponent(release.id)}&ui=0`, location.href).href; overlay.innerHTML = `Published v${release.versionNumber} · <a target="_blank" rel="noopener" href="${url}">Open</a> · <button id="copy-link">Copy link</button> · <button id="copy-embed">Copy embed</button>`; overlay.querySelector('#copy-link')?.addEventListener('click', () => navigator.clipboard.writeText(url)); overlay.querySelector('#copy-embed')?.addEventListener('click', () => navigator.clipboard.writeText(`<iframe src="${embed}" allow="fullscreen" loading="lazy"></iframe>`)) } catch (error) { overlay.textContent = error instanceof Error ? error.message : String(error) } }
  renderHierarchy(); renderInspector(); renderAssets();
}

function depth(nodes: SceneNode[], node: SceneNode): number { let count = 0; let current = node; while (current.parentId && count < 64) { const parent = nodes.find((entry) => entry.id === current.parentId); if (!parent) break; count += 1; current = parent } return count }
function escapePointer(value: string): string { return value.replace(/~/g, '~0').replace(/\//g, '~1') }
function rgbHex(color: { x: number; y: number; z: number }): string { return `#${[color.x, color.y, color.z].map((value) => Math.round(Math.max(0, Math.min(1, value)) * 255).toString(16).padStart(2, '0')).join('')}` }
function hexRgb(value: string): [number, number, number] { return [parseInt(value.slice(1, 3), 16) / 255, parseInt(value.slice(3, 5), 16) / 255, parseInt(value.slice(5, 7), 16) / 255] }
function mimeFor(extension: string): string { return ({ glb: 'model/gltf-binary', hdr: 'image/vnd.radiance', exr: 'image/x-exr', png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', webp: 'image/webp', ktx2: 'image/ktx2' } as Record<string, string>)[extension] ?? 'application/octet-stream' }
function parseGlb(file: File): Promise<any> { return new Promise(async (resolve, reject) => { const worker = new Worker(new URL('./importWorker.ts', import.meta.url), { type: 'module' }); worker.onmessage = (event) => { worker.terminate(); event.data.ok ? resolve(event.data.result) : reject(new Error(event.data.error)) }; worker.onerror = (event) => { worker.terminate(); reject(new Error(event.message)) }; worker.postMessage({ name: file.name, buffer: await file.arrayBuffer() }) }) }
function contractFromGlb(projectName: string, assetId: string, hash: string, file: File, report: any): KyxosSceneContract {
  const contract = createEmptySceneContract(projectName); contract.metadata.source = { generator: 'Kyxos Studio GLB Importer', originalFilename: file.name }; contract.assets[assetId] = { id: assetId, uri: `asset://${hash}`, contentHash: hash, kind: 'model', mimeType: file.type || 'model/gltf-binary', byteSize: file.size, name: file.name, metadata: { extensionsUsed: report.extensionsUsed, warnings: report.warnings } };
  const ids = report.nodes.map(() => crypto.randomUUID()); const materialIds = report.materials.map(() => crypto.randomUUID());
  contract.materials = Object.fromEntries(report.materials.map((source: any, index: number) => { const pbr = source.pbr ?? {}; const factor = pbr.baseColorFactor ?? [1, 1, 1, 1]; const material: SceneMaterial = { id: materialIds[index], name: source.name, baseColor: { x: factor[0], y: factor[1], z: factor[2], w: factor[3] }, metalness: pbr.metallicFactor ?? 1, roughness: pbr.roughnessFactor ?? 1, emissive: { x: source.emissiveFactor?.[0] ?? 0, y: source.emissiveFactor?.[1] ?? 0, z: source.emissiveFactor?.[2] ?? 0 }, opacity: factor[3], alphaMode: (source.alphaMode ?? 'OPAQUE').toLowerCase(), alphaCutoff: source.alphaCutoff ?? 0.5, doubleSided: source.doubleSided ?? false }; return [material.id, material] }));
  contract.nodes = report.nodes.map((source: any, index: number) => { const primitive = source.mesh != null ? report.meshes[source.mesh]?.primitives?.[0] : null; const materialId = primitive?.material != null ? materialIds[primitive.material] : undefined; return { id: ids[index], name: source.name, parentId: source.parent == null ? null : ids[source.parent], children: source.children.map((child: number) => ids[child]), transform: { position: { x: source.translation[0], y: source.translation[1], z: source.translation[2] }, rotation: { x: 0, y: 0, z: 0 }, scale: { x: source.scale[0], y: source.scale[1], z: source.scale[2] } }, visible: true, meshAssetId: source.mesh == null ? undefined : assetId, meshIndex: source.mesh, materialSlots: materialId ? [materialId] : [], cameraId: source.camera == null ? undefined : contract.activeCameraId, metadata: { gltfNodeIndex: source.index, quaternion: source.rotation } } });
  contract.animations = report.animations.map((source: any) => ({ id: crypto.randomUUID(), name: source.name, clipIndex: source.index, duration: 0, loop: true, speed: 1, autoplay: source.index === 0 })); return contract;
}

void boot();
